services:
  db:
    image: mysql:8.4
    container_name: pageblanche-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pageblanche-app
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:3000"
    labels:
      - "traefik.enable=true"
      # On utilise le réseau de ton Traefik existant
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.pageblanche.rule=Host(`cms.nino-rameau.fr`)"
      - "traefik.http.routers.pageblanche.entrypoints=websecure"
      - "traefik.http.routers.pageblanche.tls=true"
      # /!\ Vérifie si ton resolver s'appelle 'letsencrypt' ou 'myresolver' dans ton autre projet
      - "traefik.http.routers.pageblanche.tls.certresolver=letsencrypt"
      - "traefik.http.services.pageblanche.loadbalancer.server.port=3000"
    networks:
      - traefik_externe
      - internal

volumes:
  mysql_data:

networks:
  # On dit à Docker que ce réseau existe déjà sur le VPS
  traefik_externe:
    external: true
    name: traefik
  internal:
    internal: true